/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 14 14:46:03 GMT 2016
 */

package capstone.mobile.dataHandlers;

import org.junit.Test;
import static org.junit.Assert.*;
import capstone.mobile.dataHandlers.DataUnavailableException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DataUnavailableException_ESTest extends DataUnavailableException_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 5 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.DataUnavailableException.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. Branch capstone.mobile.dataHandlers.DataUnavailableException.<init>(Ljava/lang/String;)V: root-Branch in context: capstone.mobile.dataHandlers.DataUnavailableException:<init>(Ljava/lang/String;)V
   * Goal 3. capstone.mobile.dataHandlers.DataUnavailableException.<init>(Ljava/lang/String;)V: Line 7
   * Goal 4. [METHOD] capstone.mobile.dataHandlers.DataUnavailableException.<init>(Ljava/lang/String;)V
   * Goal 5. [METHODNOEX] capstone.mobile.dataHandlers.DataUnavailableException.<init>(Ljava/lang/String;)V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataUnavailableException dataUnavailableException0 = new DataUnavailableException("capstone.mobile.dataHandlers.DataUnavailableException");
  }
}
